### ISSUE TITLE
Wrong sudoers check

### ISSUE THREAD

**Issue by gedigi** [rebootuser/LinEnum#10]
Hi, I just ran the script on one of my machines and it returns:

```
Super user account(s):
root

We can sudo without supplying a password!
User user1 may run the following commands on localhost:
    (ALL) ALL
```

However, the line in sudoers doesn't have the NOPASSWD item, so that statement is not accurate. Is this a bug or am I misunderstanding the message?

Thanks!

**Comment by rebootuser** [comment]
Valid issue - fix seems clean, will test on a few systems and merge.

**Comment by rebootuser** [comment]
As per thread; changes have been made in v0.9 and details have been added to contributors file.
