### ISSUE TITLE
Better structure and other tool

### ISSUE THREAD

**Issue by diego-treitos** [rebootuser/LinEnum#31]
Hello guys, first of all thank you for your awesome project!

Some days ago I wanted to add some functionality to your script but I saw that there was a lot of room for improvement regarding the structure so I forked your repository and started organizing and modularizing some things. Using functions to call the tests saved a lot of code and shrinked the size of the file by several hundreds of lines. However I realised that I needed to change too much for what I wanted to do so I ended giving up and starting from zero.
I would like to point out where my fork is in case you want to get some ideas from there: https://github.com/diego-treitos/LinEnum
I also added some tests and fixed others.

Just in case you are interested, I have publised also my script for enumeration. I am trying to show by default the most important information for a privesc. I used many tests from your script, although rewritten and added a bunch more. Hopefully we can colaborate to improve both.
https://github.com/diego-treitos/linux-smart-enumeration

**Comment by rebootuser** [comment]
Cheers for reaching out and good to see LinEnum has inspired your project. I'll definitely take a look and happy to share ideas/checks going forward.
