### ISSUE TITLE
Sort files by date

### ISSUE THREAD

**Issue by tehmoon** [rebootuser/LinEnum#32]
Hi! Thank you for the amazing script!!

I've found myself multiple time having trouble locating interesting files because there are so many, so I like at the created/updated date because interesting files are most likely to be the most recent ones.

I would like to make an addition to that script something like: 

```find . -printf "%T@ %Tc %p\n" | sort -n```

Which would numerically sort files by date. I don't know if that's something you would want, but I can try to come up with a good way without adding too much dependencies and try to stay as portable as possible.

**Comment by rebootuser** [comment]
Hi. Sorting by date sounds like a good idea. If you make a PR with the desired changes I'll get it sorted. Thanks for getting involved in the project!

**Comment by tehmoon** [comment]
Sounds good! I was actually working on it right now, but did not finish yet.

**Comment by rebootuser** [comment]
Closed issue due at this time. If this functionality is something that's requested further down the line, happy to revisit it.
