### ISSUE TITLE
ists world-writable suid files

### ISSUE THREAD

**Issue by jimmyzhangau** [rebootuser/LinEnum#34]
Hi,
To find world writable suid files, the following script is used,
wwsuid=`find / -perm -4007 -type f -exec ls -la {} 2>/dev/null \;`

Should it be:
wwsuid=`find / -perm -4002 -type f -exec ls -la {} 2>/dev/null \;`

Cheers,
JJ

**Comment by rebootuser** [comment]
This has been in years. Great spot, thanks. Changes made https://github.com/rebootuser/LinEnum/commit/ab1b72a6fa8a436eb80596760e7f4178a8ef4643
