### ISSUE TITLE
BUG: ./linenum.sh: line 46: syntax error near unexpected token `|'

### ISSUE THREAD

**Issue by royharoush** [rebootuser/LinEnum#8]
`local@local1:~$ ./linenum.sh
./linenum.sh: line 45: \n\e[00;31m##############################################                                                                                                                                                             ###########\e[00m: command not found
./linenum.sh: line 46: syntax error near unexpected token `|'
./linenum.sh: line 46: `|tee -a $report 2>/dev/null'
local@local1:~$ ./linenum.sh`

the fix is to replace all occurrences of  "\n\e[00;31m#"

![image](https://cloud.githubusercontent.com/assets/8113056/12537244/cb9ca738-c2c2-11e5-96e7-e9ff62be2901.png)

**Comment by whoot** [comment]
Install 'colorama' and you should not get any errors.
